# Generated by Django 5.2.12 on 2026-07-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(help_text='HH:MM format')),
                ('label', models.CharField(default='Alarm', max_length=100)),
                ('repeat', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily')], default='once', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('snooze_until', models.DateTimeField(blank=True, help_text='If set, alarm is snoozed until this time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
